export const postalCodes = {
  Afghanistan: '^\\d{4}$',
  'Åland Islands': '^\\d{5}$',
  Albania: '^\\d{4}$',
  Algeria: '^\\d{5}$',
  'American Samoa': '^\\d{5}(-{1}\\d{4,6})$',
  Andorra: '^[Aa][Dd]\\d{3}$',
  Angola: '',
  Anguilla: '^[Aa][I][-][2][6][4][0]$',
  'Antigua and Barbuda': '',
  Argentina: '^\\d{4}|[A-Za-z]\\d{4}[a-zA-Z]{3}$',
  Armenia: '^\\d{4}$',
  Aruba: '',
  'Ascension island': '^[Aa][Ss][Cc][Nn]\\s{0,1}[1][Zz][Zz]$',
  Australia: '^\\d{4}$',
  Austria: '^\\d{4}$',
  Azerbaijan: '^[Aa][Zz]\\d{4}$',
  Bahamas: '',
  Bahrain: '^\\d{3,4}$',
  Bangladesh: '^\\d{4}$',
  Barbados: '^[Aa][Zz]\\d{5}$',
  Belarus: '^\\d{6}$',
  Belgium: '^\\d{4}$',
  Belize: '',
  Benin: '',
  Bermuda: '^[A-Za-z]{2}\\s([A-Za-z]{2}|\\d{2})$',
  Bhutan: '^\\d{5}$',
  Bolivia: '^\\d{4}$',
  'Bonaire, Sint Eustatius and Saba': '',
  'Bosnia and Herzegovina': '^\\d{5}$',
  Botswana: '',
  Brazil: '^\\d{5}-\\d{3}$',
  'British Antarctic Territory': '^[Bb][Ii][Qq]{2}\\s{0,1}[1][Zz]{2}$',
  'British Indian Ocean Territory': '^[Bb]{2}[Nn][Dd]\\s{0,1}[1][Zz]{2}$',
  'British Virgin Islands': '^[Vv][Gg]\\d{4}$',
  Brunei: '^[A-Za-z]{2}\\d{4}$',
  Bulgaria: '^\\d{4}$',
  'Burkina Faso': '',
  Burundi: '',
  Cambodia: '^\\d{5}$',
  Cameroon: '',
  Canada: '^(?=[^DdFfIiOoQqUu\\d\\s])[A-Za-z]\\d(?=[^DdFfIiOoQqUu\\d\\s])[A-Za-z]\\s{0,1}\\d(?=[^DdFfIiOoQqUu\\d\\s])[A-Za-z]\\d$',
  'Cape Verde': '^\\d{4}$',
  'Cayman Islands': '^[Kk][Yy]\\d[-\\s]{0,1}\\d{4}$',
  'Central African Republic': '',
  Chad: '^\\d{5}$',
  Chile: '^\\d{7}\\s\\(\\d{3}-\\d{4}\\)$',
  China: '^\\d{6}$',
  'Christmas Island': '^\\d{4}$',
  'Cocos (Keeling) Island': '^\\d{4}$',
  Colombia: '^\\d{6}$',
  Comoros: '',
  'Congo (Brazzaville)': '',
  'Congo, Democratic Republic': '^[Cc][Dd]$',
  'Cook Islands': '',
  'Costa Rica': '^\\d{4,5}$',
  "Côte d'Ivoire (Ivory Coast)": '',
  Croatia: '^\\d{5}$',
  Cuba: '^\\d{5}$',
  'Curaçao': '',
  Cyprus: '^\\d{4}$',
  'Czech Republic': '^\\d{5}\\s\\(\\d{3}\\s\\d{2}\\)$',
  Denmark: '^\\d{4}$',
  Djibouti: '',
  Dominica: '',
  'Dominican Republic': '^\\d{5}$',
  'East Timor': '',
  Ecuador: '^\\d{6}$',
  'El Salvador': '^1101$',
  Egypt: '^\\d{5}$',
  'Equatorial Guinea': '',
  Eritrea: '',
  Estonia: '^\\d{5}$',
  Ethiopia: '^\\d{4}$',
  'Falkland Islands': '^[Ff][Ii][Qq]{2}\\s{0,1}[1][Zz]{2}$',
  'Faroe Islands': '^\\d{3}$',
  Fiji: '',
  Finland: '^\\d{5}$',
  France: '^\\d{5}$',
  'French Guiana': '^973\\d{2}$',
  'French Polynesia': '^987\\d{2}$',
  'French Southern and Antarctic Territories': '',
  Gabon: '^\\d{2}\\s[a-zA-Z-_ ]\\s\\d{2}$',
  Gambia: '',
  Georgia: '^\\d{4}$',
  Germany: '^\\d{5}$',
  Ghana: '',
  Gibraltar: '^[Gg][Xx][1]{2}\\s{0,1}[1][Aa]{2}$',
  Greece: '^\\d{3}\\s{0,1}\\d{2}$',
  Greenland: '^\\d{4}$',
  Grenada: '',
  Guadeloupe: '^971\\d{2}$',
  Guam: '^\\d{5}$',
  Guatemala: '^\\d{5}$',
  Guernsey: '^[A-Za-z]{2}\\d\\s{0,1}\\d[A-Za-z]{2}$',
  Guinea: '',
  'Guinea Bissau': '^\\d{4}$',
  Guyana: '',
  Haiti: '^\\d{4}$',
  'Heard and McDonald Islands': '^\\d{4}$',
  Honduras: '^\\d{5}$',
  'Hong Kong': '',
  Hungary: '^\\d{4}$',
  Iceland: '^\\d{3}$',
  India: '^\\d{6}$',
  Indonesia: '^\\d{5}$',
  Iran: '^\\d{5}-\\d{5}$',
  Iraq: '^\\d{5}$',
  Ireland: '',
  'Isle of Man': '^[Ii[Mm]\\d{1,2}\\s\\d\\[A-Z]{2}$',
  Israel: '^\\b\\d{5}(\\d{2})?$',
  Italy: '^\\d{5}$',
  Jamaica: '^\\d{2}$',
  Japan: '^\\d{7}\\s\\(\\d{3}-\\d{4}\\)$',
  Jersey: '^[Jj][Ee]\\d\\s{0,1}\\d[A-Za-z]{2}$',
  Jordan: '^\\d{5}$',
  Kazakhstan: '^\\d{6}$',
  Kenya: '^\\d{5}$',
  Kiribati: '',
  'Korea, North': '',
  'Korea, South': '^\\d{6}\\s\\(\\d{3}-\\d{3}\\)$',
  Kosovo: '^\\d{5}$',
  Kuwait: '^\\d{5}$',
  Kyrgyzstan: '^\\d{6}$',
  Latvia: '^[Ll][Vv][- ]{0,1}\\d{4}$',
  Laos: '^\\d{5}$',
  Lebanon: '^\\d{4}\\s{0,1}\\d{4}$',
  Lesotho: '^\\d{3}$',
  Liberia: '^\\d{4}$',
  Libya: '^\\d{5}$',
  Liechtenstein: '^\\d{4}$',
  Lithuania: '^[Ll][Tt][- ]{0,1}\\d{5}$',
  Luxembourg: '^\\d{4}$',
  Macau: '',
  Macedonia: '^\\d{4}$',
  Madagascar: '^\\d{3}$',
  Malawi: '',
  Maldives: '^\\d{4,5}$',
  Malaysia: '^\\d{5}$',
  Mali: '',
  Malta: '^[A-Za-z]{3}\\s{0,1}\\d{4}$',
  'Marshall Islands': '^\\d{5}$',
  Mauritania: '',
  Mauritius: '',
  Martinique: '^972\\d{2}$',
  Mayotte: '^976\\d{2}$',
  Micronesia: '^\\d{5}$',
  Mexico: '^\\d{5}$',
  Moldova: '^[Mm][Dd][- ]{0,1}\\d{4}$',
  Monaco: '^980\\d{2}$',
  Mongolia: '^\\d{5}$',
  Montenegro: '^\\d{5}$',
  Montserrat: '^[Mm][Ss][Rr]\\s{0,1}\\d{4}$',
  Morocco: '^\\d{5}$',
  Mozambique: '^\\d{4}$',
  Myanmar: '^\\d{5}$',
  Namibia: '^\\d{5}$',
  Nauru: '',
  Nepal: '^\\d{5}$',
  Netherlands: '^\\d{4}\\s{0,1}[A-Za-z]{2}$',
  'New Caledonia': '^988\\d{2}$',
  'New Zealand': '^\\d{4}$',
  Nicaragua: '^\\d{5}$',
  Niger: '^\\d{4}$',
  Nigeria: '^\\d{6}$',
  Niue: '',
  'Norfolk Island': '^\\d{4}$',
  'Northern Mariana Islands': '^\\d{5}$',
  Norway: '^\\d{4}$',
  Oman: '^\\d{3}$',
  Pakistan: '^\\d{5}$',
  Palau: '^\\d{5}$',
  Panama: '^\\d{6}$',
  'Papua New Guinea': '^\\d{3}$',
  Paraguay: '^\\d{4}$',
  Peru: '^\\d{5}$',
  Philippines: '^\\d{4}$',
  'Pitcairn Islands': '^[Pp][Cc][Rr][Nn]\\s{0,1}[1][Zz]{2}$',
  Poland: '^\\d{2}[- ]{0,1}\\d{3}$',
  Portugal: '^\\d{4}[- ]{0,1}\\d{3}$',
  'Puerto Rico': '^\\d{5}$',
  Qatar: '',
  'Réunion': '^974\\d{2}$',
  Romania: '^\\d{6}$',
  Russia: '^\\d{6}$',
  'Saint Barthélemy': '^97133$',
  'Saint Helena': '^[Ss][Tt][Hh][Ll]\\s{0,1}[1][Zz]{2}$',
  'Saint Kitts and Nevis': '',
  'Saint Lucia': '',
  'Saint Martin': '^97150$',
  'Saint Pierre and Miquelon': '^97500$',
  'Saint Vincent and the Grenadines': '^[Vv][Cc]\\d{4}$',
  'San Marino': '^4789\\d$',
  'Sao Tome and Principe': '',
  'Saudi Arabia': '^\\d{5}(-{1}\\d{4})?$',
  Senegal: '^\\d{5}$',
  Serbia: '^\\d{5}$',
  Seychelles: '',
  'Sint Maarten': '',
  'Sierra Leone': '',
  Singapore: '^\\d{6}$',
  Slovakia: '^\\d{5}\\s\\(\\d{3}\\s\\d{2}\\)$',
  Slovenia: '^([Ss][Ii][- ]{0,1}){0,1}\\d{4}$',
  'Solomon Islands': '',
  Somalia: '',
  'South Africa': '^\\d{4}$',
  'South Georgia and the South Sandwich Islands': '^[Ss][Ii][Qq]{2}\\s{0,1}[1][Zz]{2}$',
  'South Korea': '^\\d{6}\\s\\(\\d{3}-\\d{3}\\)$',
  Spain: '^\\d{5}$',
  'Sri Lanka': '^\\d{5}$',
  Sudan: '^\\d{5}$',
  Suriname: '',
  Swaziland: '^[A-Za-z]\\d{3}$',
  Sweden: '^\\d{3}\\s*\\d{2}$',
  Switzerland: '^\\d{4}$',
  'Svalbard and Jan Mayen': '^\\d{4}$',
  Syria: '',
  Taiwan: '^\\d{5}$',
  Tajikistan: '^\\d{6}$',
  Tanzania: '',
  Thailand: '^\\d{5}$',
  Togo: '',
  Tokelau: '',
  Tonga: '',
  'Trinidad and Tobago': '^\\d{6}$',
  'Tristan da Cunha': '^[Tt][Dd][Cc][Uu]\\s{0,1}[1][Zz]{2}$',
  Tunisia: '^\\d{4}$',
  Turkey: '^\\d{5}$',
  Turkmenistan: '^\\d{6}$',
  'Turks and Caicos Islands': '^[Tt][Kk][Cc][Aa]\\s{0,1}[1][Zz]{2}$',
  Tuvalu: '',
  Uganda: '',
  Ukraine: '^\\d{5}$',
  'United Arab Emirates': '',
  'United Kingdom': '^[A-Z]{1,2}[0-9R][0-9A-Z]?\\s*[0-9][A-Z-[CIKMOV]]{2}',
  'United States': '^\\b\\d{5}\\b(?:[- ]{1}\\d{4})?$',
  Uruguay: '^\\d{5}$',
  'U.S. Virgin Islands': '^\\d{5}$',
  Uzbekistan: '^\\d{3} \\d{3}$',
  Vanuatu: '',
  Vatican: '^120$',
  Venezuela: '^\\d{4}(\\s[a-zA-Z]{1})?$',
  Vietnam: '^\\d{6}$',
  'Wallis and Futuna': '^986\\d{2}$',
  Yemen: '',
  Zambia: '^\\d{5}$',
  Zimbabwe: ''
}

export const postalCodeMask = {
  "United States": "99999",
  "Canada": "A9A-9A9",
  "United Kingdom": undefined,
  "Argentina": "A9999AAA",
  "Australia": "9999",
  "Austria": "9999",
  "Belgium": "9999",
  "Brazil": "99999-999",
  "Bulgaria": "9999",
  "Cambodia": "99999",
  "Chile": "999-9999",
  "Colombia": "999999",
  "Croatia": "99999",
  "Denmark": "9999",
  "Ecuador": "999999",
  "Egypt": "99999",
  "Estonia": "99999",
  "Finland": "99999",
  "France": "99999",
  "Germany": "99999",
  "Greece": "99 99",
  "Guatemala": "99999",
  "Hungary": "9999",
  "India": "999 999",
  "Indonesia": "99999",
  "Ireland": undefined,
  "Italy": "99999",
  "Jordan": "99999",
  "Kuwait": "99999",
  "Latvia": "9999",
  "Lithuania": "99999",
  "Luxembourg": "99999",
  "Malaysia": "99999",
  "Malta": "AAA 9999",
  "Mexico": "99999",
  "Montenegro": "99999",
  "Netherlands": "9999 AA",
  "NNew Zealand": "9999",
  "Norway": "9999",
  "Oman": "999",
  "Pakistan": "99999",
  "Paraguay": "9999",
  "Peru": "99999",
  "Philippines": "9999",
  "Poland": "99-999",
  "Portugal": "9999-999",
  "Romania": "999999",
  "Russia": "999999",
  "Serbia": "99999",
  "Singapore": "999999",
  "Slovenia": "9999",
  "Spain": "99999",
  "Sweden": undefined,
  "Switzerland": "9999",
  "Taiwan": undefined,
  "Tanzania": "99999",
  "Thailand": "99999",
  "Tunisia": "9999",
  "Turkey": "99999",
  "Ukraine": "99999",
  "Uruguay": "99999",
  "Venezuela": "9999-A",
  "Vietnam": "999999"
}