# fly.toml app configuration file generated for famun on 2025-05-12T20:05:01Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'famun'
primary_region = 'gig'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
